# Generated by Django 2.1.5 on 2019-01-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backGround', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dto',
        ),
    ]
