# Generated by Django 2.1.5 on 2019-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backGround', '0002_delete_dto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('isPublic', models.BooleanField(default=True)),
            ],
        ),
    ]
