# Generated by Django 2.1.5 on 2019-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backGround', '0003_dto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dto',
            name='isSend',
            field=models.BooleanField(default=False),
        ),
    ]
